### ISSUE TITLE
Why is type of initial state a function?

### ISSUE THREAD

**Issue by diegopamio** [troch/reinspect#5]
I see that the typings of the setState signature first parameter is a function, even when in the examples, an object is passed. Any clue?

**Comment by troch** [comment]
For `useState` the first argument is like React's `useState`: a function returning an initial state, or an initial state. The type of your initial state is free (number, boolean, string, object...)

**Comment by diegopamio** [comment]
That's not what `useState.d.ts` says:

`export declare const useState: <S>(initialState: () => S, id: string | number) => [S, import("react").Dispatch<import("react").SetStateAction<S>>];
`

from that it could be a function returning an initial state, but not an initial state. I'm missing something?

**Comment by MrStobbart** [comment]
I had the same issue and looked it up in the [react types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts). I created a pull request to fix it https://github.com/troch/reinspect/pull/6 :)

**Comment by troch** [comment]
Oh I see now. Typings are generated, not manually defined. No idea why the type of useState is wrong given https://github.com/troch/reinspect/blob/master/src/useState.ts#L11
